name: Add New Post

on:
  repository_dispatch:
    types: [new_post]

jobs:
  update-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format Date
        id: date
        run: |
          echo "DATE=$(date +"%b %d %Y")" >> $GITHUB_ENV

      - name: Insert New Post
        run: |
          NEW_POST="  {
    author: '${{ github.event.client_payload.author }}',
    content: '${{ github.event.client_payload.content }}',
    date: '${{ env.DATE }}',
    like: '0'
  },"
          
          awk -v newpost="$NEW_POST" '
            /const posts = \[/ { 
              print;
              print newpost;
              next
            }
            { print }
          ' js/server.js > js/temp_server.js
          mv js/temp_server.js js/server.js

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add js/server.js
          git commit -m "New post by ${{ github.event.client_payload.author }}"
          git push
